vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: /media/posts
            upload_destination: '%kernel.project_dir%/public/media/posts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_image:
            uri_prefix: /media/users
            upload_destination: '%kernel.project_dir%/public/media/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        pub_image:
            uri_prefix: /media/pubs
            upload_destination: '%kernel.project_dir%/public/media/pubs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
